In [4]:
import tensorflow as tf

In [7]:
# 基本数据运算
data1 = tf.placeholder(tf.float32)
data2 = tf.placeholder(tf.float32)
dataAdd = tf.add(data1, data2)
with tf.Session() as sess:
    print(sess.run(dataAdd,feed_dict={data1: 6, data2: 2})) 
print('end!')

8.0
end!


In [13]:
# 矩阵的定义
data1 = tf.constant([[6, 6]])
data2 = tf.constant([[2],
                     [2]])
data3 = tf.constant([[3, 3]])
data4 = tf.constant([[1, 2],
                     [3, 4],
                     [5, 6]])
print(data4.shape)# 维度
with tf.Session() as sess:
    print(sess.run(data4))
    print(sess.run(data4[0]))
    print(sess.run(data4[0, 1]))
    print(sess.run(data4[:, 0]))

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
[1 2]
2
[1 3 5]


In [15]:
# 矩阵的操作
data1 = tf.constant([[6, 6]])
data2 = tf.constant([[2],
                     [2]])
data3 = tf.constant([[3, 3]])
data4 = tf.constant([[1, 2],
                     [3, 4],
                     [5, 6]])
matMul = tf.matmul(data1, data2)
matAdd = tf.add(data1, data3)
with tf.Session() as sess:
    print(sess.run(matMul)) # 1行1列
    print(sess.run(matAdd)) # 1行2列
    print(sess.run([matAdd, matMul])) # 1行2列

[[24]]
[[9 9]]
[array([[9, 9]]), array([[24]])]


In [18]:
# 定义一个特殊矩阵
mat0 = tf.zeros([2, 3]) # 全0
mat1 = tf.ones([3, 2]) # 全1
mat2 = tf.fill([3, 2], 12) #填充矩阵
with tf.Session() as sess:
    print(sess.run(mat0))
    print(sess.run(mat1))
    print(sess.run(mat2))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[12 12]
 [12 12]
 [12 12]]


In [21]:
mat1 = tf.constant([[2], [3], [4]])
mat2 = tf.zeros_like(mat1)
mat3 = tf.zeros_like(mat1)
with tf.Session() as sess:
    print(sess.run(mat2))

[[0]
 [0]
 [0]]


In [22]:
# 对某两个值之间的距离进行切分
mat = tf.linspace(0.0, 2.0, 11)
with tf.Session() as sess:
    print(sess.run(mat))

[ 0.          0.2         0.40000001  0.60000002  0.80000001  1.
  1.20000005  1.39999998  1.60000002  1.80000007  2.        ]


In [24]:
# 随机数矩阵
mat = tf.random_uniform([2, 3], -1, 2)#产生一个从-1到2之间的随机数的 2*3矩阵
with tf.Session() as sess:
    print(sess.run(mat))

[[-0.19722772  1.53765297  1.0741508 ]
 [-0.0737803   0.58286488  0.75293767]]
